version: "3"
services:
    sztafeta:
        image: ghcr.io/kuchtek/sztafeta/webapp:latest
        ports:
            -  "8888"
        volumes:
            - ./data:/sztafeta/data_collector
    nginx: 
        image: nginx:latest
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - sztafeta
        ports:
        - "21298:80"

    data_collector:
        image: ghcr.io/kuchtek/sztafeta/collector:latest
        volumes:
            - ./data:/data_collector/data
        deploy:
            restart_policy:
                condition: any
            update_config:
                delay: 5m
