version: "3"
services:
    sztafeta:
       image: sztafeta:0.1-min
       build:
           context: .
       ports:
           -  "8888"
    nginx: 
        image: nginx:latest
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - sztafeta
        ports:
        - "21298:80"