---
name: Deploy Sztafeta To VPS
on:
    push:
    pull_request:
    workflow_dispatch:
env:
    USER_PATH: /home/frog/
jobs:
    check:
        name: Check environment and secrets
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              id: check-gh-key-secret
              shell: bash
              run: |
                if [[ ! -z  "${{ secrets.VPS_PASSWORD }}" ]] && 
                    [[ ! -z  "${{ secrets.VPS_USERNAME }}" ]] && 
                    [[ ! -z  "${{ secrets.VPS_HOST }}" ]]  &&  
                    [[ ! -z "${{ secrets.URI }}" ]] && 
                    [[ ! -z "${{ secrets.CLIENT_ID }}" ]] && 
                    [[ ! -z "${{ secrets.CLIENT_SECRET }}" ]] && 
                    [[ ! -z "${{secrets.STRAVA_CLIENT_ID }}" ]] && 
                    [[ ! -z "${{ secrets.STRAVA_CLIENT_SECRET }}" ]] && 
                    [[ ! -z "${{ secrets.FLASK_SECRET_KEY }}" ]]; then
                    echo "All secrets are declared."
                    echo "declared=true" >> $GITHUB_OUTPUT;
                else
                    echo "At least one secret is missing: VPS_PASSWORD, VPS_USERNAME, VPS_HOST, URI, CLIENT_ID, CLIENT_SECRET, FLASK_SECRET_KEY, STRAVA_CLIENT_ID, STRAVA_CLIENT_SECRET, ."
                    exit 1
                fi
        outputs:
            has_gh_secrets: ${{ steps.check-gh-key-secret.outputs.declared }}
    prepare-environment:
        needs: [check]
        runs-on: ubuntu-latest
        name: Prepare environment
        if: needs.check.outputs.has_gh_secrets
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                ref: master
            - name: Pass environment variables
              run: |
                echo "URI = \"${{ secrets.URI }}\"" >> .env
                echo "CLIENT_ID = \"${{ secrets.CLIENT_ID }}\"" >> .env
                echo "CLIENT_SECRET = \"${{ secrets.CLIENT_SECRET }}\"" >> .env
                echo "STRAVA_CLIENT_ID = \"${{ secrets.STRAVA_CLIENT_ID }}\"" >> .env
                echo "StRAVA_CLIENT_SECRET = \"${{ secrets.STRAVA_CLIENT_SECRET }}\"" >> .env
                echo "FLASK_SECRET_KEY = \"${{ secrets.FLASK_SECRET_KEY }}\"" >> .env
            - name: Zip files
              run: zip -r sztafeta.zip . -x ./.venv -x ./.vscode
            - name: copy files via ssh password
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.VPS_HOST}}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                port: 11298
                source: ./sztafeta.zip
                target: ${{ env.USER_PATH }}
                overwrite: true
            - name: Unzip files
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                port: 11298
                script: unzip -o sztafeta.zip ${{ env.USER_PATH}}sztafeta/

    deploy-docker:
        name: Deploy to VPS 
        runs-on: ubuntu-latest
        needs: [prepare-environment]
        steps:
            - name: Deploy to VPS over SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                port: 11298
                script_stop: true
                script: |
                    cd ${{ env.USER_PATH}}/sztafeta
                    echo ${{ secrets.VPS_PASSWORD }} | sudo -S ./rebuild.sh